### ISSUE TITLE
Run an additional regression in analyze_data from year 1960 onward

### ISSUE THREAD

**Issue by lawrencech3n** [lawrencech3n/gentzkow#2]
The goal of the issue is to modify the code in the analysis folder ([`~/analysis/code/analyze_data.py`](https://github.com/lawrencech3n/gentzkow/blob/41def95677610ce04f0be4d363d2b0d3ebb2dc43/analysis/code/analyze_data.py)) so that the regression in [`~/paper_slides/output/paper.pdf`](https://github.com/lawrencech3n/gentzkow/blob/41def95677610ce04f0be4d363d2b0d3ebb2dc43/paper_slides/output/paper.pdf) shows an additional regression from year 1960 onward. This follows from the [Practice Task Instructions](https://github.com/gslab-econ/lab-manual/wiki/Practice-Task).

**Comment by snairdesai** [comment]
Thanks for the work @lawrencech3n! I might recommend completing these issues in sequence (i.e., finish #1 and open a PR with us assigned before you start issue #2). This will prevent ["merge conflicts"](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/about-merge-conflicts) down the road.

**Comment by lawrencech3n** [comment]
[Latest version of code](https://github.com/lawrencech3n/gentzkow/tree/6df6d5f9f3276cf089e03a02acea46d6c50e5e09)
[Issue subfolder](https://github.com/lawrencech3n/gentzkow/tree/6df6d5f9f3276cf089e03a02acea46d6c50e5e09/analysis)
[Issue branch prior to merging](https://github.com/lawrencech3n/gentzkow/blob/41def95677610ce04f0be4d363d2b0d3ebb2dc43/analysis/code/analyze_data.py)
